=== uo293873/sew-2025/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinadorPrincipal" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadasOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacionMundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidades" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="km"/>
								<xs:enumeration value="m"/>
								<xs:enumeration value="millas"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidades" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="m"/>
								<xs:enumeration value="km"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	
	<xs:element name="numeroVueltas">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="200"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="localidad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="pais">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="patrocinadorPrincipal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="referencia" type="xs:string" />
	
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto" minOccurs="1" maxOccurs="5" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="foto" type="xs:string" />
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" minOccurs="1" maxOccurs="3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="video" type="xs:string" />
	
	<xs:element name="coordenadasOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudGeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="longitudGeo">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-180"/>
				<xs:maxInclusive value="180"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="latitudGeo">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-90"/>
				<xs:maxInclusive value="90"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="altitudGeo">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="9000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tramo" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="km"/>
								<xs:enumeration value="m"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudGeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrePiloto" />
				<xs:element ref="tiempoCarrera" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombrePiloto">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="tiempoCarrera" type="xs:duration" />
	
	<xs:element name="clasificacionMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pilotoClasificado" minOccurs="3" maxOccurs="3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="pilotoClasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrePilotoClasificado" />
				<xs:element ref="puntosPiloto" />
			</xs:sequence>
			<xs:attribute name="posicion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nombrePilotoClasificado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="puntosPiloto">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="1000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== uo293873/sew-2025/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.uniovi.es">
    <nombre>Petronas Sepang International Circuit</nombre>
    
    <longitud unidades="m">5540</longitud>
    
    <anchura unidades="m">16</anchura>
    
    <fecha>2025-10-26</fecha>
    
    <horaInicio>08:00:00</horaInicio>
    
    <numeroVueltas>20</numeroVueltas>
    
    <localidad>Sepang</localidad>
    
    <pais>Malasia</pais>
    
    <patrocinadorPrincipal>Petronas</patrocinadorPrincipal>
    
    <referencias>
        <referencia>https://www.motogp.com/es/calendar/2025/event/malaysia/c2cd8f49-5643-440f-84fc-4c37b3ef3f87?tab=circuit-info</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Sepang</referencia>
        <referencia>https://www.sepangcircuit.com/</referencia>
    </referencias>
    
    <fotos>
        <foto>multimedia/sepang_panorama.jpg</foto>
        <foto>multimedia/sepang_recta.png</foto>
        <foto>multimedia/sepang_tramos.png</foto>
    </fotos>
    
    <videos>
        <video>multimedia/track_lap_sepang.mp4</video>
    </videos>
    
    <coordenadasOrigen>
        <longitudGeo>101.7383756</longitudGeo>
        <latitudGeo>2.7607531</latitudGeo>
        <altitudGeo>35.98</altitudGeo>
    </coordenadasOrigen>
    
    <tramos>
        <tramo>
            <distancia unidades="m">616.79</distancia>
            <coordenadas>
                <longitudGeo>101.7328390</longitudGeo>
                <latitudGeo>2.7603226</latitudGeo>
                <altitudGeo>37.90</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">29.37</distancia>
            <coordenadas>
                <longitudGeo>101.7326400</longitudGeo>
                <latitudGeo>2.7604965</latitudGeo>
                <altitudGeo>37.64</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">26.49</distancia>
            <coordenadas>
                <longitudGeo>101.7326180</longitudGeo>
                <latitudGeo>2.7607337</latitudGeo>
                <altitudGeo>37.51</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">34.52</distancia>
            <coordenadas>
                <longitudGeo>101.7328290</longitudGeo>
                <latitudGeo>2.7609616</latitudGeo>
                <altitudGeo>37.12</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">64.89</distancia>
            <coordenadas>
                <longitudGeo>101.7333978</longitudGeo>
                <latitudGeo>2.7608282</latitudGeo>
                <altitudGeo>35.64</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">23.19</distancia>
            <coordenadas>
                <longitudGeo>101.7335728</longitudGeo>
                <latitudGeo>2.7609420</latitudGeo>
                <altitudGeo>35.17</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">29.22</distancia>
            <coordenadas>
                <longitudGeo>101.7335513</longitudGeo>
                <latitudGeo>2.7612039</latitudGeo>
                <altitudGeo>34.20</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">58.25</distancia>
            <coordenadas>
                <longitudGeo>101.7332334</longitudGeo>
                <latitudGeo>2.7616205</latitudGeo>
                <altitudGeo>31.23</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">68.33</distancia>
            <coordenadas>
                <longitudGeo>101.7330698</longitudGeo>
                <latitudGeo>2.7622129</latitudGeo>
                <altitudGeo>27.53</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">95.71</distancia>
            <coordenadas>
                <longitudGeo>101.7332008</longitudGeo>
                <latitudGeo>2.7630636</latitudGeo>
                <altitudGeo>23.51</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">70.22</distancia>
            <coordenadas>
                <longitudGeo>101.7335642</longitudGeo>
                <latitudGeo>2.7635804</latitudGeo>
                <altitudGeo>22.58</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">58.73</distancia>
            <coordenadas>
                <longitudGeo>101.7340156</longitudGeo>
                <latitudGeo>2.7638555</latitudGeo>
                <altitudGeo>22.57</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidades="m">193.33</distancia>
            <coordenadas>
                <longitudGeo>101.7356666</longitudGeo>
                <latitudGeo>2.7644064</latitudGeo>
                <altitudGeo>36.67</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">217.58</distancia>
            <coordenadas>
                <longitudGeo>101.7374712</longitudGeo>
                <latitudGeo>2.7651679</latitudGeo>
                <altitudGeo>36.57</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">23.23</distancia>
            <coordenadas>
                <longitudGeo>101.7376351</longitudGeo>
                <latitudGeo>2.7650381</latitudGeo>
                <altitudGeo>37.29</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">241.5</distancia>
            <coordenadas>
                <longitudGeo>101.7380690</longitudGeo>
                <latitudGeo>2.7629099</latitudGeo>
                <altitudGeo>39.97</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">50.04</distancia>
            <coordenadas>
                <longitudGeo>101.7383169</longitudGeo>
                <latitudGeo>2.7625341</latitudGeo>
                <altitudGeo>37.85</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">78.9</distancia>
            <coordenadas>
                <longitudGeo>101.7389548</longitudGeo>
                <latitudGeo>2.7622218</latitudGeo>
                <altitudGeo>36.32</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">61.96</distancia>
            <coordenadas>
                <longitudGeo>101.7395095</longitudGeo>
                <latitudGeo>2.7622808</latitudGeo>
                <altitudGeo>36.46</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">84.97</distancia>
            <coordenadas>
                <longitudGeo>101.7400830</longitudGeo>
                <latitudGeo>2.7627866</latitudGeo>
                <altitudGeo>37.80</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">67.3</distancia>
            <coordenadas>
                <longitudGeo>101.7406477</longitudGeo>
                <latitudGeo>2.7630061</latitudGeo>
                <altitudGeo>38.68</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">70.02</distancia>
            <coordenadas>
                <longitudGeo>101.7412354</longitudGeo>
                <latitudGeo>2.7627781</latitudGeo>
                <altitudGeo>38.62</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidades="m">309.5</distancia>
            <coordenadas>
                <longitudGeo>101.7430443</longitudGeo>
                <latitudGeo>2.7606608</latitudGeo>
                <altitudGeo>38.81</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">110.6</distancia>
            <coordenadas>
                <longitudGeo>101.7426547</longitudGeo>
                <latitudGeo>2.7597454</latitudGeo>
                <altitudGeo>38.00</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">477.25</distancia>
            <coordenadas>
                <longitudGeo>101.7383839</longitudGeo>
                <latitudGeo>2.7592718</latitudGeo>
                <altitudGeo>34.04</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">19.27</distancia>
            <coordenadas>
                <longitudGeo>101.7383406</longitudGeo>
                <latitudGeo>2.7591040</latitudGeo>
                <altitudGeo>34.65</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="m">95.75</distancia>
            <coordenadas>
                <longitudGeo>101.7390549</longitudGeo>
